platform :ios, '8.0'
workspace 'DemoApp'
xcodeproj 'DemoApp/DemoApp'
link_with 'DemoApp'
use_frameworks!

target :'DemoApp' do

  pod 'GustyAppKit'
  # pod 'GustyLib', :path => '/Users/mschroeder/myfiles/projects/Xcode6/GustyLib/GustyLib_development'
  # pod 'GustyLib', :git => 'https://bitbucket.org/marcelo_schroeder/gustylib.git', :branch => 'development'
  # pod 'GustyLib', :git => 'https://bitbucket.org/marcelo_schroeder/gustylib.git', :tag => '0.1.7'

end
