platform :ios, '8.0'
workspace 'DemoApp'
xcodeproj 'DemoApp/DemoApp'
link_with 'DemoApp'
use_frameworks!

target :'DemoApp' do

   pod 'GustyKit', :path => '/Users/mschroeder/myfiles/projects/Xcode/GustyKit/GustyKit_development'
  # pod 'GustyKit', :git => 'https://github.com/marcelo-schroeder/GustyKit.git', :branch => 'dev_NextVersion'

#  pod 'GustyAppKit'
   pod 'GustyAppKit', :path => '/Users/mschroeder/myfiles/projects/Xcode/GustyAppKit/GustyAppKit_development'

end
